# Generated by Django 6.0.dev20250825080545 on 2025-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
