# Generated by Django 6.0.dev20250825080545 on 2025-08-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_solution_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='<Sans Titre>', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(),
        ),
    ]
