# Generated by Django 6.0.dev20250825080545 on 2025-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_category_problem_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
