# Generated by Django 6.0.dev20250825080545 on 2025-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('meca', 'Mécanique'), ('opt', 'Optique'), ('ond', 'Ondes'), ('thermo', 'Thermodynamique'), ('elec', 'Électromagnétisme'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
