# Generated by Django 6.0.dev20250825080545 on 2025-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_category_alter_problem_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('meca', 'Mécanique'), ('opt', 'Optique'), ('ond', 'Ondes'), ('thermo', 'Thermodynamique'), ('elec', 'Électromagnétisme'), ('autre', 'Autre')], default='autre', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(),
        ),
    ]
