# Generated by Django 6.0.dev20250825080545 on 2025-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_difficulty_alter_problem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
