# Generated by Django 6.0.dev20250825080545 on 2025-10-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_submission_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='correct_answer',
            new_name='expected_solution',
        ),
    ]
