# Generated by Django 6.0.dev20250825080545 on 2025-10-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_rename_correct_answer_problem_expected_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='expected_solution',
        ),
    ]
