# Generated by Django 6.0.dev20250825080545 on 2025-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_remove_problem_expected_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correct_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='total_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
