# Generated by Django 6.0.dev20250825080545 on 2025-10-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemsuggestion',
            old_name='submitted_at',
            new_name='suggested_at',
        ),
    ]
