# Generated by Django 6.0.dev20250825080545 on 2025-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
