# Generated by Django 6.0.dev20250825080545 on 2025-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
