# Generated by Django 6.0.4 on 2026-10-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
